---
apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  annotations:
    helm.sh/resource-policy: "keep"
  labels:
    app: "istio-pilot"
    chart: "istio"
    heritage: "Tiller"
    release: "istio"
  name: "gateways.networking.istio.io"
spec:
  group: "networking.istio.io"
  names:
    categories:
    - "istio-io"
    - "networking-istio-io"
    kind: "Gateway"
    listKind: "GatewayList"
    plural: "gateways"
    shortNames:
    - "gw"
    singular: "gateway"
  scope: "Namespaced"
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          description: "%gateways.yaml.spec.validation.openAPIV3Schema.properties.spec"
          properties:
            selector:
              additionalProperties:
                format: "string"
                type: "string"
              type: "object"
            servers:
              description: "%gateways.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.servers"
              items:
                properties:
                  bind:
                    format: "string"
                    type: "string"
                  defaultEndpoint:
                    format: "string"
                    type: "string"
                  hosts:
                    description: "%gateways.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.servers.items.properties.hosts"
                    items:
                      format: "string"
                      type: "string"
                    type: "array"
                  port:
                    properties:
                      name:
                        description: "%gateways.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.servers.items.properties.port.properties.name"
                        format: "string"
                        type: "string"
                      number:
                        description: "%gateways.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.servers.items.properties.port.properties.number"
                        type: "integer"
                      protocol:
                        description: "%gateways.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.servers.items.properties.port.properties.protocol"
                        format: "string"
                        type: "string"
                    type: "object"
                  tls:
                    description: "%gateways.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.servers.items.properties.tls"
                    properties:
                      caCertificates:
                        description: "%gateways.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.servers.items.properties.tls.properties.caCertificates"
                        format: "string"
                        type: "string"
                      cipherSuites:
                        description: "%gateways.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.servers.items.properties.tls.properties.cipherSuites"
                        items:
                          format: "string"
                          type: "string"
                        type: "array"
                      credentialName:
                        format: "string"
                        type: "string"
                      httpsRedirect:
                        type: "boolean"
                      maxProtocolVersion:
                        description: "%gateways.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.servers.items.properties.tls.properties.maxProtocolVersion"
                        enum:
                        - "TLS_AUTO"
                        - "TLSV1_0"
                        - "TLSV1_1"
                        - "TLSV1_2"
                        - "TLSV1_3"
                        type: "string"
                      minProtocolVersion:
                        description: "%gateways.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.servers.items.properties.tls.properties.minProtocolVersion"
                        enum:
                        - "TLS_AUTO"
                        - "TLSV1_0"
                        - "TLSV1_1"
                        - "TLSV1_2"
                        - "TLSV1_3"
                        type: "string"
                      mode:
                        enum:
                        - "PASSTHROUGH"
                        - "SIMPLE"
                        - "MUTUAL"
                        - "AUTO_PASSTHROUGH"
                        - "ISTIO_MUTUAL"
                        type: "string"
                      privateKey:
                        description: "%gateways.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.servers.items.properties.tls.properties.privateKey"
                        format: "string"
                        type: "string"
                      serverCertificate:
                        description: "%gateways.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.servers.items.properties.tls.properties.serverCertificate"
                        format: "string"
                        type: "string"
                      subjectAltNames:
                        items:
                          format: "string"
                          type: "string"
                        type: "array"
                      verifyCertificateHash:
                        items:
                          format: "string"
                          type: "string"
                        type: "array"
                      verifyCertificateSpki:
                        items:
                          format: "string"
                          type: "string"
                        type: "array"
                    type: "object"
                type: "object"
              type: "array"
          type: "object"
      type: "object"
  versions:
  - name: "v1alpha3"
    served: true
    storage: true
  - name: "v1beta1"
    served: true
    storage: false
