---
apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  annotations:
    helm.sh/resource-policy: "keep"
  labels:
    app: "istio-pilot"
    chart: "istio"
    heritage: "Tiller"
    release: "istio"
  name: "sidecars.networking.istio.io"
spec:
  group: "networking.istio.io"
  names:
    categories:
    - "istio-io"
    - "networking-istio-io"
    kind: "Sidecar"
    listKind: "SidecarList"
    plural: "sidecars"
    singular: "sidecar"
  scope: "Namespaced"
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          description: "%sidecars.yaml.spec.validation.openAPIV3Schema.properties.spec"
          properties:
            egress:
              items:
                properties:
                  bind:
                    format: "string"
                    type: "string"
                  captureMode:
                    enum:
                    - "DEFAULT"
                    - "IPTABLES"
                    - "NONE"
                    type: "string"
                  hosts:
                    items:
                      format: "string"
                      type: "string"
                    type: "array"
                  port:
                    description: "%sidecars.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.egress.items.properties.port"
                    properties:
                      name:
                        description: "%sidecars.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.egress.items.properties.port.properties.name"
                        format: "string"
                        type: "string"
                      number:
                        description: "%sidecars.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.egress.items.properties.port.properties.number"
                        type: "integer"
                      protocol:
                        description: "%sidecars.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.egress.items.properties.port.properties.protocol"
                        format: "string"
                        type: "string"
                    type: "object"
                type: "object"
              type: "array"
            ingress:
              items:
                properties:
                  bind:
                    description: "%sidecars.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.ingress.items.properties.bind"
                    format: "string"
                    type: "string"
                  captureMode:
                    enum:
                    - "DEFAULT"
                    - "IPTABLES"
                    - "NONE"
                    type: "string"
                  defaultEndpoint:
                    format: "string"
                    type: "string"
                  port:
                    description: "%sidecars.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.ingress.items.properties.port"
                    properties:
                      name:
                        description: "%sidecars.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.ingress.items.properties.port.properties.name"
                        format: "string"
                        type: "string"
                      number:
                        description: "%sidecars.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.ingress.items.properties.port.properties.number"
                        type: "integer"
                      protocol:
                        description: "%sidecars.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.ingress.items.properties.port.properties.protocol"
                        format: "string"
                        type: "string"
                    type: "object"
                type: "object"
              type: "array"
            outboundTrafficPolicy:
              description: "%sidecars.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.outboundTrafficPolicy"
              properties:
                mode:
                  enum:
                  - "REGISTRY_ONLY"
                  - "ALLOW_ANY"
                  type: "string"
              type: "object"
            workloadSelector:
              properties:
                labels:
                  additionalProperties:
                    format: "string"
                    type: "string"
                  type: "object"
              type: "object"
          type: "object"
      type: "object"
  versions:
  - name: "v1alpha3"
    served: true
    storage: true
  - name: "v1beta1"
    served: true
    storage: false
